export const LOGIN_SUCCESS_ACT = 'LOGIN_SUCCESS_ACT';
export const LOGIN_FAILURE_ACT = 'LOGIN_FAILURE_ACT';
export const LOGOUT_ACT = 'LOGOUT_ACT';
export const CLEAR_LOGIN_ERROR_ACT = 'CLEAR_LOGIN_ERROR_ACT';
